### ISSUE TITLE
Unable to use the library properly after installation.

### ISSUE THREAD

**Issue by zsy-suyang** [LemurPwned/video-sampler#11]
Hello author, your work is very good. But when I used the video sampler library you posted, I didn't make any unnecessary actions. After installation, I directly called the library, but kept reporting the following errors, so I couldn't use it properly. I look forward to your answer and would like to thank you again for your work.

![image](https://github.com/LemurPwned/video-sampler/assets/150314475/0d5977d2-cbe7-4e66-ab07-b9e9ea35866c)

**Comment by LemurPwned** [comment]
@zsy-suyang hey! 
I think I know what's that -- I use the typing scheme introduced in Python 3.9
See here: https://docs.python.org/3.9/library/typing.html

so in you case, you have Python3.8 then `dict` is not available for typing.
Are you able to test with Python 3.9 or higher?
If not, I'll make a branch compatible with older versions.
