### ISSUE TITLE
warning: The package `typer==0.12.5` does not have an extra named `all`

### ISSUE THREAD

**Issue by fcakyon** [LemurPwned/video-sampler#28]
Thanks for the great package!

When I run: 

```bash
pip install video_sampler==0.11.0
```

I get this warning: 

```bash
warning: The package `typer==0.12.5` does not have an extra named `all`
```

Removing `[all]` in this line would fix that I believe:

https://github.com/LemurPwned/video-sampler/blob/72ec1bb58790a7e7d21e9e5bc07d22cd41bf0544/pyproject.toml#L34

**Comment by LemurPwned** [comment]
@fcakyon thanks for spotting this! Let me fix that -- I also noticed we're missing `pyaml` from requirements

**Comment by fcakyon** [comment]
Thank you for the fast response @LemurPwned !

Can you please check this issue as well? https://github.com/LemurPwned/video-sampler/issues/29 🙏🏻
