### ISSUE TITLE
FR: eliminate redundant frames given a list of frames (instead of video)

### ISSUE THREAD

**Issue by fcakyon** [LemurPwned/video-sampler#38]
## 🚀 Feature Request

Optionally accept a list of frames as input instead of a video file when performing sample selection.

## 🔈 Motivation

In my use case, I have a list of frame samples from different videos or clips of the same video. I want to use video-sampler package to eliminate redundant samples in this list. To my knowledge, video-sampler only accepts video files as input.

## 🛰 Alternatives

Converting the list of frames into a video and processing it with video-sampler?

## 📎 Additional context

If this use case is possible with the current version of the video-sampler, please direct me to related docs/scripts.

**Comment by LemurPwned** [comment]
@fcakyon You're right, it's not currently supported. 

I guess that it'd be relatively easy to add support for accepting an ordered list of files (or a file of ordered list of files).
But that's the crux -- we need to have a concept of some ordering, because the deduplication relies on a temporal buffer as opposed to a global buffer of all frames. 

If you think this approach would be useful, I could maybe propose some sketch towards the end of the week.

**Comment by fcakyon** [comment]
> I guess that it'd be relatively easy to add support for accepting an ordered list of files (or a file of ordered list of files). But that's the crux -- we need to have a concept of some ordering, because the deduplication relies on a temporal buffer as opposed to a global buffer of all frames.
> 
> If you think this approach would be useful, I could maybe propose some sketch towards the end of the week.

@LemurPwned Yes, that sounds perfect! There can be a requirement for an input frame list being ordered.

I want to clarify one point, though. I have to perform this duplication as fast as possible in my use case. Thus, exporting the list of frames into a disk and providing the file paths to the video-sample would significantly increase the latency. Would it be possible to give an iterator/generator of frames as a numpy array or bytes to the video-sampler, or would a list of file paths be a hard requirement?

**Comment by LemurPwned** [comment]
@fcakyon that makes sense
The user could provide a folder or a glob-compatible pattern. Then, the requirement would be that the frame files can be lexicographically sorted. In other words, if frames are numbered, those numbers need to be zero-padded to a fixed length substring. 

A further improvement could dynamically eval user's sorting function passed in as a string, though not sure of other considerations of that solution atm.

**Comment by LemurPwned** [comment]
@fcakyon happy to reiterate if you have feedback -- just reopen if something's still missing or it's too slow

**Comment by fcakyon** [comment]
Hey @LemurPwned current implementation works fine for me however in one of my use cases, I have to perform keyframe detection on a live video stream. So I need frame based sampling to work on a list of in memory frame files (or numpy arrays) instead of frame files available on disk. What should be my approach in this case?

**Comment by LemurPwned** [comment]
@fcakyon with the current implementation (for example yt-dlp integration works like that) you can probably just hook up to the video stream directly and sample from that live feed.

**Comment by fcakyon** [comment]
Thank you @LemurPwned ill check for your youtube implementation!

**Comment by LemurPwned** [comment]
Just testing some rtsp streams and it might be that I need to handle a few more edge cases (frame rate is not defined, frame pts are not exactly the same, and it never ends :)). But finite video urls should work.

**Comment by LemurPwned** [comment]
Ok seems like it's working fine now, see #40

**Comment by fcakyon** [comment]
Thank you so much! @LemurPwned
