### ISSUE TITLE
Need help with ClipGate parameters

### ISSUE THREAD

**Issue by fcakyon** [LemurPwned/video-sampler#42]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/LemurPwned/video-sampler/issues).

## ❓ Question

1. If I want more frames to pass in ClipGate, then pos_margin needs to be smaller, and neg_margin has to be larger, right? 
2. Do you know if adding 'a photo of' prefix increases the quality of similarity scores as pos_samples=['a photo of a person', 'a photo of a face'] ?

cc: @LemurPwned

**Comment by LemurPwned** [comment]
@fcakyon 
1. Correct, a sample will be rejected if it gets too close to any of negative samples or it's too far away from a "closest" positive sample. So, making a positive threshold smaller will include more samples on the positive side (closer to what you want). Reducing the negative threshold may also help, but it's less useful I'd say, unless your sample positive and negative prompts are not discriminative respective to each other. You could check if they are discriminative enough by embedding them and looking up their similarity score in your CLIP's version latent space. 

2. That depends on the frame/video. I noticed that it indeed makes a difference, but it boils down to what works for your video domain best. `A photo of X` or `A picture of X` seems to be working well in higher quality videos (such as film materiel) but not too great for say short-form handheld forms. 
As to why it works, I can't offer a rigorous explanation -- it's what the OpenAI seems to have been doing with their clip prompts as well, so I followed:
https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb

**Comment by fcakyon** [comment]
Thank you for the quick response! I will experiment further.

I have one more question, @LemurPwned : when I increase the batch size from 64 to 512 with CUDA available in PyTorch, I notice no change in the duration of the Hash Buffer + ClipGate sampling. Are there any other bottlenecks that could be causing the Clip inference to not be the determining factor in the duration?

**Comment by LemurPwned** [comment]
I can see how this can make little difference. 

Although I haven't profiled anything with clip gating, I suspect there are some large bottlenecks. The gating itself happens in the same thread as decoding and other processing, save for actual file ops. This is not ideal, and probably it should be delegated to another process. Aside from that, the bottlenecks are most likely: 

1. Video decoding -- that is the largest problem, and usually decoding will be a bottleneck no matter what happens, even when it's run in a separate process. This is ultra slow especially if you choose to decode all the frames, not just keyframes.
One way to speed it up is to use parallelism in the decoding process, pyav supports this. Another one is to use GPU for decoding, which should speed things up a LOT. I can see two options:

 - There's a fork of PyAV for GPU, looks interesting, but I have never tested it: https://github.com/materight/PyAV-CUDA 
 - PyAV should support hardware acceleration through opts: https://github.com/PyAV-Org/PyAV/issues/451. This one should give some speedup, although I'm pretty sure it's not as good as the original nvidia decoding libraries such as DALI: https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.readers.video.html. I think this DALI part can be more or-less easily adapted in the sampler here. 

2. The preprocessing for clip is done serially, not in parallel -- doing that in parallel could give a slight boost in speed.
3. Hashing buffer is serial right now. Though it is designed to be super lightweight, it can still bring some overhead.

**Comment by fcakyon** [comment]
By keyframes, you mean frames sampled at each min_frame_interval_sec duration, am i right?

**Comment by LemurPwned** [comment]
Actually, this is a specific option enabled by default: https://github.com/LemurPwned/video-sampler/blob/7e8a6f2bbaa91e2dd6fc58c553c0c895ba814594/video_sampler/config.py#L76 

It essentially avoids decoding every frame and decodes keyframes [I-frames specifically](https://en.wikipedia.org/wiki/Video_compression_picture_types). This means that it does not require decoding any other frames in before or after a given I-frame, thus making the entire decoding process much faster. 

The interval just spaces the decoded frames (rejects samples if they are too close to each other), whether they are keyframes or not.

**Comment by fcakyon** [comment]
Thank you for your understanding and patience. I did some research, and it turns out that i-frames are very helpful for my situation!

Feel free to connect with me on LinkedIn. I’m happy to answer any questions related to RAGs, LLMs, or vision-language models if you need assistance.
